
#Update all the sections by editing the data.yml file inside _data folder.

name: My Resume
description: A beautiful Jekyll theme for creating resume
#base_url: 'http://webjeda.com'

theme:
  enabled: false # this theme does not *have a theme*



# TODO below not supported

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic teal oceanstale
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

